### ISSUE TITLE
I can't change the volume when comments are visible

### ISSUE THREAD

**Issue by GitAcc53** [ynshung/better-yt-shorts#108]
After I click and open the comment section on PC, I can't change the volume.

**Comment by adsuth** [comment]
Yeah, I think this is because when the volume slider was first added, the comments would appear in a modal, and not a side panel.

The actions list seems to overlap the volume slider when the panel opens as it pushes them onto the video itself.

It may be a better to have the volume appear horizontally on the top row instead (styled similarly to full videos), though that may conflict with other extensions
