### ISSUE TITLE
Extension stopped working today

### ISSUE THREAD

**Issue by GitAcc53** [ynshung/better-yt-shorts#122]
I tried in Chrome and Brave. It stopped working since a few hours ago.

**Comment by HealingArcYT** [comment]
can confirm for brave. after restart today it didnt work anymore and i almost lost my hearing because for some reason videos were absolutely eardrum-blasting loud

**Comment by Silverfoenix** [comment]
Can confirm both old Extension (2.7.2) & new (2.8.3) stopped working Today using Microsoft Edge
Version 117.0.2045.43 (Official build) (64-bit)

**Comment by Waghabond** [comment]
Did a quick inspection. this line in the extension's code is broken: 
` var progBarList = overlayList.children[3].children[0].children[0];`.

Its because, the overlay element has had an extra child added above the progress bar. 

A more robust way to retrieve the same element that the broken line is trying to get is 
`overlayList.querySelector('#progress-bar-line')`. 

Hopefully that will fix the issue because it retrieves the element by its unique ID, which is unlikely to change.

**Comment by ynshung** [comment]
Submitted the patch to Chrome Web Store and Firefox Add-ons, will be published in a few hours. Thanks everyone for the report!
