### ISSUE TITLE
Progress bar stopped displaying again

### ISSUE THREAD

**Issue by neilgrz** [ynshung/better-yt-shorts#175]
**Describe the bug**
Progress bar stopped displaying on all Shorts videos

**Desktop (please complete the following information):**

- OS: win 10
- Browser: Firefox
- Version: 119.0.1

**Additional context**
Was working up to a couple days ago.

**Comment by neilgrz** [comment]
Anyone else experiencing this? Isn't this one of the main reasons people use it? Is this extension dead?

**Comment by neilgrz** [comment]
New version was released. Is anyone going to acknowledge this problem? Is it working for other people? I had no luck.

**Comment by ynshung** [comment]
I couldn't reproduce this issue at my end unfortunately, could you (or anyone facing this issue) see if the console log (F12 > Console) shows any error related to the extension to help check the root cause of the problem?

**Comment by neilgrz** [comment]
Thanks for acknowledging. I looked further and discovered this is only a problem when I'm logged into YouTube. That seems very odd so I checked on another computer. Logged off of YouTube, progress bar shows; logged in, does not show. The problem is starting to feel personal. lol. I haven't changed any of my YouTube or Google account settings before this problem. It just happened. I tried changing some of my account settings but no success. If I find anything, I'll report back.

**Comment by artism90** [comment]
Can confirm this issue on the latest Chrome version (119.0.6045.160), too.

What I found out:
* Progress bar is bugged when logged into brand channel which contains hundreds of subscriptions and dozens of playlists.
* Progress bar successfully shows when logged off as well as when logged in with my almost empty personal account (non-brand-channel) with only one active subscription and no playlists created and probably most settings still set at default.

Apparently the bug lies somewhere beneath a heavily customized channel, making the progress bar disappear. If someone wants to narrow the cause further down, create a blank new channel (the progress bar should be working then) and go on adding a number of subscriptions and playlists + tweaking any channel settings until the bug comes up again.

**Comment by neilgrz** [comment]
Working again in latest version. Thanks so much.
