### ISSUE TITLE
Exception catching for failure in selecting elements

### ISSUE THREAD

**Issue by ynshung** [ynshung/better-yt-shorts#185]
There have been two instances of failure in element selection (#178, #183) where problems outlined in #184 occurred every time. To avoid any future instances, there should be an exception catching in one of the stages (preferably catch-all and not individually in each selector) but if there's any better idea feel free to throw them around

Expected behavior: When one of the injection fails (progress bar/autoplay/etc.), it should not affect other components or the extension onthe whole.

**Comment by adsuth** [comment]
definitely overdesigning this, but i think this could do with a robust plan.

Current thoughts would be to, instead of storing the id of shorts that successfully injected, we could create an InjectionState object that stores the whether each element succeeded, failed, etc.

So for example of what that could entail:

`InjectionState`:
- id: of the short
- fullInjectionComplete: boolean, so we only need to check once
- items: list of InjectionStateUnits populated on initialisation such that it can be expanded

`InjectionStateUnit`:
- name: eg, what this unit is for (volume slider, action element, etc)
- state: SUCCEEDED, FAILED, NEW
- callback: the method that is called to inject this unit

These state objects are then added to the set instead; checking for injection is as simple as checking if fullInjectionComplete is true, if not, try inject all FAILED elements again.

When an element fails injection, show a toaster menu to user saying that it failed. Clicking it could link to this issues page

for error handling, we'd wrap callback in a try catch.
The catch displays the toaster, and sets the state to failed


not sure of the feasibility mind you, but i'll look into it later on. I'm in a painfully java mind at the moment

**Comment by ynshung** [comment]
Implemented on #195
