### ISSUE TITLE
feature request: show upload time

### ISSUE THREAD

**Issue by pgr-a** [ynshung/better-yt-shorts#45]
why cant we know when a short was uploaded? usually this is my main criterion to decide if i want to watch a video.
if there is no way to get to this information, an idea would be to use the time of the oldest comment.

**Comment by ynshung** [comment]
Hello @pgr-a, you can find out the uploaded date by going to the bottom-right corner and clicking the button with three dot, then click the description to display the uploaded date. For the time I don't think it's possible since there isn't any way (perhaps using API) to fetch the upload time client-side.

**Comment by pgr-a** [comment]
i know, but thats hard. may i ask you to put the date under this button?
